### ISSUE TITLE
conform to asset lib standard

### ISSUE THREAD

**Issue by aMOPel** [raldone01/godot_addon_gdlogging#1]
Thanks for your work. This looks like a great logger :+1: 

I know the way asset lib handles installation weirdly, not even having a proper version management.
I assume that's why you wrote your git submodule installation instructions.
But like this you can't easily install this plugin properly over the asset lib client.

https://docs.godotengine.org/en/latest/community/asset_library/submitting_to_assetlib.html#recommendations

**Comment by raldone01** [comment]
Thanks for bringing this to my attention.
I tried to work around it and released a new version.
Once my asset lib changes get approved I will test if the install works.
I don't understand why they chose such a weird addon structure.
