### ISSUE TITLE
Error using Log.Logger.trace: Trying to assign value of type 'int' to a variable of type 'String'

### ISSUE THREAD

**Issue by likadev** [raldone01/godot_addon_gdlogging#2]
Hello,

I'm receiving an error on this line in logger.gd:474 in the LogRecordFormatter#format() method:

`var line: String = frame["line"]`

because `frame["line"]` is an integer and it expects "`line`" to be a String.

I'm calling it like this (using a ConsoleSink):

```
var log := Log.Logger.new("Player")

log.trace("hp: %f, maxhp: %f, mana: %f, maxmana: %f, hp+: %f, mp+: %f" % [ health, max_health, mana, max_mana, health_regeneration, mana_regeneration ])
```

Changing the type to `int` or wrapping `frame["line"]` in a `str()` call to convert it to String first solves the issue.

**Comment by raldone01** [comment]
Fixed in `v1.1.1`.
